entries/urls.py
from django.urls import path

from .views import (EntryListView, EntryDetailView, EntryCreateView,
                    EntryUpdateView, EntryDeleteView, EntryShareView, EntryShareCheckView)

app_name = 'entries'
urlpatterns = [
    path('', EntryListView.as_view(), name='list'),
    path('entry/create/', EntryCreateView.as_view(), name='create'),
    path('entry/<int:pk>/', EntryDetailView.as_view(), name='detail'),
    path('entry/<int:pk>/update/', EntryUpdateView.as_view(), name='update'),
    path('entry/<int:pk>/delete/', EntryDeleteView.as_view(), name='delete'),
    path('entry/<int:pk>/share/', EntryShareView.as_view(), name='share'),
    path('entry/share/<str:hash>/<int:time>/<int:pk>/', EntryShareCheckView.as_view(),
         name='share-check')
]

manager/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('users.urls')),
    path('', include('entries.urls'))
]

users/urls.py
from django.urls import path

from users.views import SinginView, LogoutView

app_name = 'users'
urlpatterns = [
    path('signin/', SinginView.as_view(), name='signin'),
    path('logout/', LogoutView.as_view(), name='logout')
]

common/templates/base.html
{% load static %}<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="author" content="Mateusz Furga">
    <meta name="keywords" content="web, password, password-manager">
    <meta name="theme-color" content="#fff">

    <link rel="stylesheet" type="text/css" href="{% static 'common.css' %}">

    <title>{% block title %} &middot; Password Manager{% endblock %}</title>

    {% block head %} {% endblock %}
</head>
<body>
    <nav id="navbar">
        <div class="container clear">
            <h1 class="fleft">Web Password Manager</h1>
            {% if user.is_authenticated %}
            <ul class="navbar-list fright">
                <li itemprop="name">{{ request.user }}</li>
                <li itemprop="name"><a itemprop="url" href="{% url 'entries:create' %}">new entry</a></li>
                <li itemprop="name"><a itemprop="url" href="{% url 'users:logout' %}">logout</a></li>
            </ul>
            {% endif %}
        </div>
    </nav>
    {% if messages %}<ul class="messages container">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>{% endif %}
    {% block content %}{% endblock %}
    <footer id="footer" class="container tcenter p20">
        <p>Source code available on <a href="https://github.com/mfurga/web-password-manager">Github</a></p>
        <p>Web Password Manager by Mateusz Furga</p>
    </footer>
</body>
</html>